Search.appendIndex(
    [
                {
            "fqsen": "\\Actualitzar",
            "name": "Actualitzar",
            "summary": "",
            "url": "classes/Actualitzar.html"
        },                {
            "fqsen": "\\Actualitzar\u003A\u003Aactualizar\u0028\u0029",
            "name": "actualizar",
            "summary": "",
            "url": "classes/Actualitzar.html#method_actualizar"
        },                {
            "fqsen": "\\Connexio",
            "name": "Connexio",
            "summary": "",
            "url": "classes/Connexio.html"
        },                {
            "fqsen": "\\Connexio\u003A\u003AobtenirConnexio\u0028\u0029",
            "name": "obtenirConnexio",
            "summary": "",
            "url": "classes/Connexio.html#method_obtenirConnexio"
        },                {
            "fqsen": "\\Connexio\u003A\u003A\u0024host",
            "name": "host",
            "summary": "",
            "url": "classes/Connexio.html#property_host"
        },                {
            "fqsen": "\\Connexio\u003A\u003A\u0024usuario",
            "name": "usuario",
            "summary": "",
            "url": "classes/Connexio.html#property_usuario"
        },                {
            "fqsen": "\\Connexio\u003A\u003A\u0024contrase\u00F1a",
            "name": "contrase\u00F1a",
            "summary": "",
            "url": "classes/Connexio.html#property_contrase%C3%B1a"
        },                {
            "fqsen": "\\Connexio\u003A\u003A\u0024baseDatos",
            "name": "baseDatos",
            "summary": "",
            "url": "classes/Connexio.html#property_baseDatos"
        },                {
            "fqsen": "\\Eliminar",
            "name": "Eliminar",
            "summary": "",
            "url": "classes/Eliminar.html"
        },                {
            "fqsen": "\\Eliminar\u003A\u003Aeliminar\u0028\u0029",
            "name": "eliminar",
            "summary": "M\u00E9todo\u0020para\u0020eliminar\u0020un\u0020producto\u0020de\u0020la\u0020base\u0020de\u0020datos\n\u0020Una\u0020vez\u0020eliminado\u0020recarga\u0020la\u0020tabla\u0020de\u0020productos\u0020redireccionando\u0020a\u0020la\u0020pagina\u0020principal",
            "url": "classes/Eliminar.html#method_eliminar"
        },                {
            "fqsen": "\\Footer",
            "name": "Footer",
            "summary": "",
            "url": "classes/Footer.html"
        },                {
            "fqsen": "\\Footer\u003A\u003AmostrarFooter\u0028\u0029",
            "name": "mostrarFooter",
            "summary": "",
            "url": "classes/Footer.html#method_mostrarFooter"
        },                {
            "fqsen": "\\Header",
            "name": "Header",
            "summary": "",
            "url": "classes/Header.html"
        },                {
            "fqsen": "\\Header\u003A\u003AmostrarHeader\u0028\u0029",
            "name": "mostrarHeader",
            "summary": "",
            "url": "classes/Header.html#method_mostrarHeader"
        },                {
            "fqsen": "\\Modificar",
            "name": "Modificar",
            "summary": "",
            "url": "classes/Modificar.html"
        },                {
            "fqsen": "\\Modificar\u003A\u003AmostrarFormulari\u0028\u0029",
            "name": "mostrarFormulari",
            "summary": "",
            "url": "classes/Modificar.html#method_mostrarFormulari"
        },                {
            "fqsen": "\\Nou",
            "name": "Nou",
            "summary": "",
            "url": "classes/Nou.html"
        },                {
            "fqsen": "\\Nou\u003A\u003AmostrarFormulari\u0028\u0029",
            "name": "mostrarFormulari",
            "summary": "Funcio\u0020para\u0020mostrar\u0020formulario\nMuestra\u0020los\u0020campos\u0020necesarios\u0020para\u0020poder\u0020insertar\u0020un\u0020producto",
            "url": "classes/Nou.html#method_mostrarFormulari"
        },                {
            "fqsen": "\\Nou\u003A\u003AnouProducte\u0028\u0029",
            "name": "nouProducte",
            "summary": "M\u00E9todo\u0020para\u0020insertar\u0020un\u0020nuevo\u0020producto\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Nou.html#method_nouProducte"
        },                {
            "fqsen": "\\Principal",
            "name": "Principal",
            "summary": "",
            "url": "classes/Principal.html"
        },                {
            "fqsen": "\\Principal\u003A\u003AmostrarProductes\u0028\u0029",
            "name": "mostrarProductes",
            "summary": "",
            "url": "classes/Principal.html#method_mostrarProductes"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
